# Generated by Django 6.0.3 on 2026-04-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_me', '0002_audioupload_imageupload_videoupload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioupload',
            name='allow_external_sharing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audioupload',
            name='is_research',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='allow_external_sharing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='is_research',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='allow_external_sharing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_research',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videoupload',
            name='allow_external_sharing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videoupload',
            name='is_research',
            field=models.BooleanField(default=False),
        ),
    ]
